-- MySQL Script generated by MySQL Workbench
-- Thu Feb 18 21:40:40 2021
-- Model: DataBase    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Personne`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Personne` (
  `CIN` INT NOT NULL,
  `Prenom` VARCHAR(30) NOT NULL,
  `Nom` VARCHAR(30) NOT NULL,
  `DateNaissance` DATE NOT NULL,
  `Ville` VARCHAR(30) NOT NULL,
  `NumTel` INT NOT NULL,
  `Email` VARCHAR(100) NOT NULL,
  `Photo` BLOB NOT NULL,
  PRIMARY KEY (`CIN`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Compte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Compte` (
  `EID` INT NOT NULL,
  `MDP` VARCHAR(50) NOT NULL,
  `Admin` INT NOT NULL,
  `DateInscription` DATE NOT NULL,
  `Salaire` INT NOT NULL,
  `Personne_CIN` INT NOT NULL,
  PRIMARY KEY (`EID`, `Personne_CIN`),
  INDEX `fk_Inscription_Personne1_idx` (`Personne_CIN` ASC) VISIBLE,
  CONSTRAINT `fk_Inscription_Personne1`
    FOREIGN KEY (`Personne_CIN`)
    REFERENCES `mydb`.`Personne` (`CIN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tache`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tache` (
  `TID` INT NOT NULL,
  `TacheNom` VARCHAR(30) NOT NULL,
  `DirecteurEID` VARCHAR(30) NOT NULL,
  `Inscription_EID` INT NOT NULL,
  PRIMARY KEY (`TID`, `Inscription_EID`),
  INDEX `fk_Tache_Inscription1_idx` (`Inscription_EID` ASC) VISIBLE,
  CONSTRAINT `fk_Tache_Inscription1`
    FOREIGN KEY (`Inscription_EID`)
    REFERENCES `mydb`.`Compte` (`EID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
